'use strict';

const APP_KEY = 'aiRoleplayStudio_history_v2';
const SETTINGS_KEY = 'aiRoleplayStudio_settings_v2';
const DEFAULT_SETTINGS = { preferAI:true, speech:true, handsFree:true, autoSend:true, ttsEngine:'auto', voiceURI:'auto', kokoroVoice:'auto', speechRate:1, apiEndpoint:'', premiumPreview:true };
const CATEGORY_LABELS = { sales:'営業・商談', manager:'管理職面談', interview:'採用面接', support:'クレーム対応' };
const EMOTIONS = ['neutral','positive','curious','skeptical','angry'];
const KOKORO_MODEL = 'onnx-community/Kokoro-82M-v1.0-ONNX';
const KOKORO_DTYPE = 'q8';
const KOKORO_VOICES = [
  {id:'auto',label:'アバターに合わせて自動選択'},
  {id:'jm_kumo',label:'日本語男性（Kumo）',gender:'male'},
  {id:'jf_alpha',label:'日本語女性 A（Alpha）',gender:'female'},
  {id:'jf_gongitsune',label:'日本語女性 B（Gongitsune）',gender:'female'},
  {id:'jf_tebukuro',label:'日本語女性 C（Tebukuro）',gender:'female'},
  {id:'jf_nezumi',label:'日本語女性 D（Nezumi）',gender:'female'}
];

const AVATARS = [
  {id:'suzuki',name:'鈴木社長',age:'60代',industry:'建設業',role:'代表取締役',traits:'慎重・数字重視・結論を急ぐ',description:'投資効果と実現性を重視する経営者',categories:['sales','support'],voice:{kokoro:'jm_kumo',label:'落ち着いた低めの男性',rate:.90,pitch:.82,keywords:['Otoya','Ichiro','Keita','Naoki','Male']},sample:'投資効果と実行までの道筋を、具体的に説明してください。'},
  {id:'tanaka',name:'田中部長',age:'50代',industry:'製造業',role:'生産管理部長',traits:'厳しい・論理的・現場主義',description:'現場負荷と実行可能性に厳しい管理職',categories:['sales','manager'],voice:{kokoro:'jm_kumo',label:'低くゆっくりした男性',rate:.88,pitch:.86,keywords:['Otoya','Ichiro','Naoki','Male']},sample:'現場が忙しい中で、本当に実行できるのでしょうか。'},
  {id:'sato',name:'佐藤課長',age:'40代',industry:'IT業',role:'人事課長',traits:'協調的・共感型・人を重視',description:'人材育成と定着を大切にする人事責任者',categories:['sales','interview','manager'],voice:{kokoro:'jf_alpha',label:'明るく柔らかい女性',rate:1.00,pitch:1.08,keywords:['Haruka','Kyoko','Nanami','Ayumi','Female']},sample:'社員が納得して取り組める方法なのか、詳しく伺いたいです。'},
  {id:'yamamoto',name:'山本店長',age:'30代',industry:'小売業',role:'店舗マネージャー',traits:'現実的・やや消極的・忙しい',description:'日々の業務に追われ、短時間で結論を求める',categories:['sales','manager','interview','support'],voice:{kokoro:'jm_kumo',label:'若く少し早口の男性',rate:1.08,pitch:1.00,keywords:['Keita','Takumi','Daisuke','Male']},sample:'すみません、時間がないので要点から教えてください。'},
  {id:'nakamura',name:'中村さん',age:'20代',industry:'IT業',role:'若手社員',traits:'素直・向上心・不安がある',description:'前向きだが自信がなく、本音を言い切れない',categories:['manager','interview'],voice:{kokoro:'jf_nezumi',label:'明るく元気な女性',rate:1.06,pitch:1.15,keywords:['Nanami','Haruka','Ayumi','Female']},sample:'成長したいのですが、何から取り組めばよいか迷っています。'},
  {id:'takahashi',name:'高橋専務',age:'60代',industry:'卸売業',role:'専務取締役',traits:'保守的・リスク回避・疑り深い',description:'失敗リスクを最小化し、根拠を確認する役員',categories:['sales','support'],voice:{kokoro:'jm_kumo',label:'重厚で威厳のある男性',rate:.86,pitch:.78,keywords:['Otoya','Ichiro','Naoki','Male']},sample:'前例がないことには、簡単には賛成できません。'},
  {id:'ito',name:'伊藤部長',age:'40代',industry:'金融業',role:'営業推進部長',traits:'成果重視・競争心・せっかち',description:'結果とスピードを重視する営業責任者',categories:['sales','manager','interview'],voice:{kokoro:'jf_gongitsune',label:'はっきりした口調の女性',rate:1.04,pitch:1.00,keywords:['Kyoko','Haruka','Nanami','Female']},sample:'他社と比べて、御社を選ぶ理由を端的に教えてください。'},
  {id:'watanabe',name:'渡辺工場長',age:'50代',industry:'製造業',role:'工場長',traits:'現場最優先・口下手・職人気質',description:'理屈より現場で役立つかどうかを重視する',categories:['sales','manager','support'],voice:{kokoro:'jm_kumo',label:'ぶっきらぼうな男性',rate:.92,pitch:.88,keywords:['Otoya','Keita','Ichiro','Male']},sample:'理屈より、現場でどう役立つのかを教えてください。'},
  {id:'kato',name:'加藤主任',age:'30代',industry:'サービス業',role:'チーム主任',traits:'責任感・気配り・悩みが多い',description:'周囲を優先して抱え込みやすい中堅社員',categories:['manager','interview','support'],voice:{kokoro:'jf_tebukuro',label:'優しく落ち着いた女性',rate:.98,pitch:1.05,keywords:['Haruka','Kyoko','Ayumi','Female']},sample:'期待に応えたいのですが、最近少し余裕がなくて。'},
  {id:'saito',name:'斎藤さん',age:'20代',industry:'製造業',role:'若手社員',traits:'自信がない・指示待ち・不安が強い',description:'慎重で、自分の考えを言葉にするのが苦手',categories:['manager','interview','support'],voice:{kokoro:'jm_kumo',label:'小さく控えめな男性',rate:.96,pitch:1.04,keywords:['Keita','Takumi','Male']},sample:'自分にできるか、あまり自信がありません。'}
];

const SCENARIOS = {
  sales:[
    {id:'sales_discovery',title:'課題ヒアリング',description:'表面的な悩みから本質的な課題を引き出す',sceneRole:'見込み顧客',objective:'相手の課題を具体化し、次回提案の合意を得る',hiddenNeed:'若手営業の離職と育成の遅れを本当は心配している',opening:'本日はありがとうございます。お時間は30分ほどでよろしかったでしょうか。',phases:['関係構築','現状確認','課題深掘り','合意形成'],topicLabel:'提案する商品・サービス',contextLabel:'今回の前提・背景',recommended:['suzuki','sato','tanaka','watanabe']},
    {id:'sales_proposal',title:'提案営業',description:'課題と価値を結び付け、提案への関心を高める',sceneRole:'提案を受ける担当者',objective:'提案の価値を理解してもらい、社内検討へ進める',hiddenNeed:'費用よりも、導入後に現場へ定着するかを不安に感じている',opening:'先日はヒアリングありがとうございました。今日はご提案を伺えればと思います。',phases:['導入','課題確認','価値提案','懸念対応','次回合意'],topicLabel:'提案する商品・サービス',contextLabel:'顧客課題と提案の前提',recommended:['sato','ito','tanaka','yamamoto']},
    {id:'sales_price',title:'価格反論への対応',description:'値引きに頼らず、価格背景と価値を整理する',sceneRole:'価格に厳しい決裁者',objective:'価格への懸念を具体化し、条件付きで検討を継続してもらう',hiddenNeed:'予算不足ではなく、投資効果を役員へ説明できないことが問題',opening:'内容は理解しました。ただ、正直なところ想定より高いですね。',phases:['反論受容','背景確認','価値再確認','条件整理'],topicLabel:'提案する商品・サービス',contextLabel:'価格・提案条件・顧客状況',recommended:['takahashi','suzuki','ito']},
    {id:'sales_closing',title:'クロージング',description:'「検討します」を具体的な次の行動へ変える',sceneRole:'社内検討を進める責任者',objective:'検討事項を明確にし、次回日程または意思決定条件を決める',hiddenNeed:'決裁者へ説明する材料が不足している',opening:'内容はよく分かりました。一度、社内で検討させてください。',phases:['反応確認','検討条件','意思決定者','次回設定'],topicLabel:'提案する商品・サービス',contextLabel:'これまでの商談経緯',recommended:['suzuki','sato','takahashi']}
  ],
  manager:[
    {id:'manager_1on1',title:'1on1面談',description:'部下の状態を理解し、本人の気づきと行動を促す',sceneRole:'面談を受ける部下',objective:'本人の悩みを言語化し、次の小さな行動を合意する',hiddenNeed:'成果が出ないことよりも、上司から期待されていないと感じている',opening:'今日はどんな話でしょうか。最近は、まあ普通です。',phases:['安心形成','状態確認','原因探索','行動合意'],topicLabel:'面談テーマ',contextLabel:'部下の状況・気になる変化',recommended:['saito','nakamura','kato','yamamoto']},
    {id:'manager_feedback',title:'評価フィードバック',description:'納得感を保ちながら、改善期待を具体的に伝える',sceneRole:'評価を受ける社員',objective:'評価理由を伝え、改善点と次期の行動目標を合意する',hiddenNeed:'評価そのものより、日頃の努力を見てもらえていないことに不満がある',opening:'評価が思ったより低かったので、理由をきちんと聞きたいです。',phases:['感情受容','事実説明','期待共有','行動合意'],topicLabel:'面談テーマ',contextLabel:'評価結果・伝えるべき事実',recommended:['kato','yamamoto','nakamura','ito']},
    {id:'manager_guidance',title:'改善指導',description:'人格を否定せず、事実と期待行動を伝える',sceneRole:'改善指導を受ける社員',objective:'問題行動への認識を合わせ、改善行動とフォロー日を決める',hiddenNeed:'仕事量が過剰だが、能力不足と思われたくなくて言えない',opening:'呼ばれた理由は、先週の件でしょうか。自分なりには対応したつもりです。',phases:['事実確認','認識共有','背景理解','改善合意'],topicLabel:'指導テーマ',contextLabel:'確認できている事実・期待行動',recommended:['saito','yamamoto','kato','watanabe']},
    {id:'manager_retention',title:'退職相談',description:'引き止めを急がず、退職意向の背景を理解する',sceneRole:'退職を検討する社員',objective:'退職意向の背景と本人の希望を把握し、次の面談を設定する',hiddenNeed:'給与よりも、今の職場で成長できる未来が見えない',opening:'少しご相談があって……退職を考えています。',phases:['受容','理由確認','希望理解','次回合意'],topicLabel:'面談テーマ',contextLabel:'本人の状況・これまでの経緯',recommended:['nakamura','saito','kato','yamamoto']}
  ],
  interview:[
    {id:'interview_midcareer',title:'中途採用面接',description:'経験の再現性と志向を深掘りする',sceneRole:'中途採用候補者',objective:'実績の背景・本人の役割・転職理由を具体化する',hiddenNeed:'現職の評価への不満より、専門性を高められないことが転職理由',opening:'本日は面接の機会をいただき、ありがとうございます。',phases:['関係形成','経験確認','深掘り','志向確認','相互理解'],topicLabel:'募集職種',contextLabel:'企業・職種・確認したい要件',recommended:['yamamoto','sato','ito','kato']},
    {id:'interview_newgrad',title:'新卒採用面接',description:'準備された回答の奥にある価値観を確認する',sceneRole:'新卒応募者',objective:'学生時代の経験と行動特性、志望理由を具体化する',hiddenNeed:'知名度ではなく、若手に任せる文化を重視している',opening:'よろしくお願いいたします。少し緊張しています。',phases:['緊張緩和','経験確認','行動深掘り','志望確認'],topicLabel:'募集職種',contextLabel:'企業・職種・面接の目的',recommended:['nakamura','saito']},
    {id:'interview_manager',title:'管理職候補面接',description:'マネジメント実績を具体的な行動と結果で確認する',sceneRole:'管理職候補者',objective:'チーム成果、育成、課題対応の再現性を見極める',hiddenNeed:'役職ではなく、事業づくりに関われる裁量を求めている',opening:'これまで営業部門でマネジメントをしてきました。本日はよろしくお願いします。',phases:['経歴確認','成果深掘り','育成確認','志向確認'],topicLabel:'募集職種',contextLabel:'求める管理職像・確認項目',recommended:['sato','ito','yamamoto','tanaka']}
  ],
  support:[
    {id:'support_delay',title:'納期遅延への対応',description:'怒りを受け止め、事実確認と具体策へ進める',sceneRole:'納期遅延に困る取引先',objective:'不満を受け止め、必要情報と次の連絡期限を合意する',hiddenNeed:'遅延自体より、自社の顧客へ説明できないことに困っている',opening:'今日届くと言われていたのに、まだ届いていません。どうなっているんですか。',phases:['感情受容','事実確認','影響確認','対応提示','期限合意'],topicLabel:'対象商品・サービス',contextLabel:'判明している事実・対応可能範囲',recommended:['watanabe','ito','suzuki','kato']},
    {id:'support_refund',title:'返金要求への対応',description:'安易に約束せず、理由と事実を確認する',sceneRole:'返金を求める利用者',objective:'返金希望の背景を確認し、規定に沿った次の対応を案内する',hiddenNeed:'返金より、期待したサポートを受けられなかった不満が強い',opening:'全然使えなかったので、今すぐ返金してください。',phases:['感情受容','状況確認','期待確認','対応案内'],topicLabel:'対象商品・サービス',contextLabel:'利用状況・返金規定・対応範囲',recommended:['kato','yamamoto','ito','saito']},
    {id:'support_custharass',title:'高圧的な要求への対応',description:'落ち着いて境界線を示し、必要に応じて引き継ぐ',sceneRole:'高圧的な利用者',objective:'対応可能範囲を明確にし、安全を保って適切にエスカレーションする',hiddenNeed:'自分の話を軽視されたと感じ、強い言い方になっている',opening:'責任者を今すぐ出してください。こんな対応は納得できません。',phases:['安全確保','感情受容','要望確認','境界提示','引継判断'],topicLabel:'対象商品・サービス',contextLabel:'発生した事実・対応ルール',recommended:['takahashi','watanabe','suzuki','ito']}
  ]
};

const PERSONAS = [
  {id:'gentle',label:'協力的',emoji:'😊',description:'比較的率直に答える'},
  {id:'cautious',label:'慎重型',emoji:'🤔',description:'根拠と安心を求める'},
  {id:'busy',label:'せっかち',emoji:'⏱️',description:'結論と効率を重視'},
  {id:'tough',label:'厳しい',emoji:'😒',description:'簡単には納得しない'},
  {id:'logical',label:'論理型',emoji:'📊',description:'数字と因果を重視'},
  {id:'emotional',label:'感情型',emoji:'💬',description:'気持ちへの反応を重視'},
  {id:'quiet',label:'本音を隠す',emoji:'😶',description:'短く曖昧に答える'},
  {id:'talkative',label:'話し好き',emoji:'🗣️',description:'話が広がりやすい'}
];
const DIFFICULTIES = [{id:'easy',label:'初級',description:'質問に答えやすい'},{id:'normal',label:'標準',description:'適度な反論がある'},{id:'hard',label:'上級',description:'本音を簡単に見せない'}];
const RUBRICS = { sales:['関係構築','質問力','傾聴・共感','課題の深掘り','提案・価値訴求','次の行動'],manager:['安心感','質問力','傾聴・共感','事実整理','本人の気づき','行動合意'],interview:['場づくり','質問設計','深掘り','具体性確認','公平性','相互理解'],support:['感情受容','事実確認','影響把握','説明の明確さ','解決策','適切な境界'] };

const LOCAL_DIALOGUE = {
  sales_discovery:[
    ['今のところ大きな問題はありませんが、若手によって成果にばらつきがあります。','ベテランと若手で、商談の進め方がかなり違います。'],
    ['若手はヒアリングが浅く、すぐ商品説明に入ってしまいます。','案件化率が落ちていて、上司の同行も増えています。'],
    ['本人たちの経験不足だけでなく、管理職が教え方を統一できていないと思います。','実は若手の離職も少し増えていて、育成の遅れを心配しています。'],
    ['まず現状を整理する提案なら、社内でも話しやすいと思います。','次回は営業部長も同席させたいので、候補日をください。']
  ],
  sales_proposal:[['まず、前回の課題が今回の提案にどう反映されているかを知りたいです。'],['内容は分かりますが、現場が本当に実践できるでしょうか。'],['導入後のフォローと、効果の確認方法を具体的に教えてください。'],['そこまで含まれるなら、社内で検討する材料になりそうです。'],['決裁者向けに、効果と進め方を一枚で整理できますか。']],
  sales_price:[['内容には関心があります。ただ、この金額の根拠が見えません。'],['予算だけの問題ではなく、役員会で投資効果を説明する必要があります。'],['成果指標と、実施しなかった場合のリスクを比較できると助かります。'],['条件が明確なら、検討は続けられます。']],
  sales_closing:[['一度、社内で整理したいと思っています。'],['気になっているのは費用と、現場の時間を確保できるかです。'],['最終決裁は社長です。説明用の資料が必要です。'],['では資料をいただき、来週もう一度お話ししましょう。']],
  manager_1on1:[['最近は普通です。特に話すほどではないと思います。'],['数字が出ていないので、自分には向いていないのかもしれません。'],['成果より、上司から期待されていない感じがつらいです。'],['まず一件、商談前に相談するところから試してみます。']],
  manager_feedback:[['努力した部分まで評価されていない気がします。'],['結果が足りないことは分かっていますが、難しい案件も担当しました。'],['どの行動を変えれば評価につながるのか、具体的に知りたいです。'],['来期の目標と確認時期が分かれば、納得して取り組めます。']],
  manager_guidance:[['自分なりには対応しました。何が問題だったのでしょうか。'],['急ぎの仕事が重なっていて、確認を省いてしまいました。'],['仕事量が多いと言うと、能力がないと思われそうで言えませんでした。'],['優先順位を相談し、次回は確認してから進めます。']],
  manager_retention:[['急に言って申し訳ありませんが、退職を考えています。'],['給与というより、この先成長できるイメージが持てません。'],['もっと責任ある仕事に挑戦したいのですが、機会がありません。'],['すぐ結論を出さず、もう一度話す機会をいただけますか。']],
  interview_midcareer:[['法人営業を6年間経験し、昨年は目標を120％達成しました。'],['重点顧客を絞り、社内の技術担当と提案を作り直しました。'],['自分が担ったのは課題整理と関係者の調整です。'],['転職理由は、より専門性を高められる環境を求めているためです。'],['御社では若いうちからどこまで裁量を持てますか。']],
  interview_newgrad:[['学生時代はサークルの運営に力を入れました。'],['参加者が減ったため、メンバーに個別に話を聞きました。'],['自分の提案で活動日を見直し、参加者が増えました。'],['若手にも仕事を任せる文化に魅力を感じています。']],
  interview_manager:[['営業部門で8人のチームを管理してきました。'],['売上だけでなく、案件管理の方法を標準化しました。'],['伸び悩む社員とは週一回、行動目標を確認しました。'],['事業づくりにも関われる裁量を求めています。']],
  support_delay:[['今日必要だと伝えていたのに、連絡もありませんでした。'],['こちらのお客様への納品が明日なので、説明できず困っています。'],['原因と、いつ届くのかをはっきり教えてください。'],['今日中に状況を連絡してもらえるなら待ちます。'],['連絡時間と担当者名を確認させてください。']],
  support_refund:[['期待していたサポートが受けられず、全く使えませんでした。'],['問い合わせても回答が遅く、期限に間に合いませんでした。'],['返金規定より、まず何が起きたのか確認してほしいです。'],['調査結果と対応日を明確にしてください。']],
  support_custharass:[['何度説明しても対応が変わらないので、怒っているんです。'],['担当者に軽く扱われたと感じました。'],['できることと、できないことを責任者から説明してください。'],['その言い方なら話を続けます。'],['責任者への引き継ぎ時間を教えてください。']]
};

const state = {
  category:'sales',scenarioId:'sales_discovery',avatarId:'suzuki',persona:'cautious',difficulty:'normal',mode:'practice',interaction:'voice',ttsEngineOverride:'auto',voiceOverride:'auto',kokoroVoiceOverride:'auto',
  topic:'',context:'',timeLimit:300,timeLeft:300,turn:0,phaseIndex:0,trust:50,interest:45,stress:20,
  conversation:[],events:[],timerId:null,isBusy:false,startedAt:null,lastResult:null,currentEmotion:'neutral',
  voiceSessionActive:false,audioStats:{speechTurns:0,fillerCount:0,totalChars:0,totalSeconds:0}
};

let settings = loadSettings();
let apiAvailable = false;
let recognition = null;
let isListening = false;
let recognitionFinalText = '';
let recognitionStartedAt = 0;
let recognitionDuration = 0;
let availableVoices = [];
let speechToken = 0;
let apiFailureShown = false;
let currentAudio = null;
let currentAudioUrl = '';
let kokoroWorker = null;
let kokoroLoadPromise = null;
let kokoroLoadResolve = null;
let kokoroLoadReject = null;
let kokoroStatus = 'idle';
let kokoroProgress = 0;
let kokoroStatusDetail = '未準備';
let kokoroRequestId = 0;
let kokoroGenerating = false;
let kokoroFallbackShown = false;
const kokoroPending = new Map();

function loadSettings(){try{return {...DEFAULT_SETTINGS,...JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')}}catch{return {...DEFAULT_SETTINGS}}}
function saveSettings(){try{localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings))}catch{}renderSettings()}
function loadHistory(){try{return JSON.parse(localStorage.getItem(APP_KEY)||'[]')}catch{return []}}
function saveHistory(items){try{localStorage.setItem(APP_KEY,JSON.stringify(items.slice(0,100)))}catch{}}
function clamp(n,min=0,max=100){return Math.max(min,Math.min(max,n))}
function escapeHtml(text){return String(text??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function scenario(){return (SCENARIOS[state.category]||[]).find(s=>s.id===state.scenarioId)||SCENARIOS[state.category][0]}
function avatar(id=state.avatarId){return AVATARS.find(a=>a.id===id)||AVATARS[0]}
function persona(){return PERSONAS.find(p=>p.id===state.persona)||PERSONAS[1]}
function difficulty(){return DIFFICULTIES.find(d=>d.id===state.difficulty)||DIFFICULTIES[1]}
function avatarImage(id,emotion='neutral'){const palette={neutral:'#90a4b8',positive:'#52c788',curious:'#64a8ff',skeptical:'#f4b85a',angry:'#ef6b6b'},color=palette[emotion]||palette.neutral,name=avatar(id).name.slice(0,1),svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200"><rect width="200" height="200" rx="36" fill="#14243a"/><circle cx="100" cy="88" r="60" fill="${color}"/><circle cx="78" cy="76" r="7"/><circle cx="122" cy="76" r="7"/><path d="M76 106q24 18 48 0" fill="none" stroke="#07111f" stroke-width="7"/><circle cx="151" cy="151" r="35" fill="#ff7a36"/><text x="151" y="164" text-anchor="middle" font-family="sans-serif" font-weight="700" font-size="38" fill="white">${name}</text></svg>`;return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`}
function getApiEndpoint(){const value=String(settings.apiEndpoint||'').trim();return value?value.replace(/\/$/,''):'/api/roleplay'}
function isRoleplayActive(){return document.getElementById('screen-roleplay')?.classList.contains('active')}

function showScreen(name){
  if(name!=='roleplay'&&state.timerId&&isRoleplayActive()){clearInterval(state.timerId);state.timerId=null}
  if(name!=='roleplay')stopVoiceRuntime(true);
  document.querySelectorAll('.screen').forEach(el=>el.classList.remove('active'));
  document.getElementById(`screen-${name}`)?.classList.add('active');
  document.querySelectorAll('.nav-btn').forEach(el=>el.classList.remove('active'));
  const navMap={home:'navHome',setup:'navStart',roleplay:'navStart',results:'navHistory',history:'navHistory',settings:'navSettings'};
  if(navMap[name])document.getElementById(navMap[name])?.classList.add('active');
  window.scrollTo({top:0,behavior:'smooth'});
  if(name==='home')renderHome();if(name==='history')renderHistory();if(name==='settings')renderSettings();
}

function startSetup(category){
  state.category=category;state.scenarioId=SCENARIOS[category][0].id;state.avatarId=scenario().recommended[0];
  state.persona=category==='support'?'emotional':'cautious';state.difficulty='normal';state.mode='practice';state.interaction='voice';state.ttsEngineOverride='auto';state.voiceOverride='auto';state.kokoroVoiceOverride='auto';
  document.getElementById('topicInput').value='';document.getElementById('contextInput').value='';document.getElementById('timeLimitSelect').value='300';
  document.getElementById('topicLabel').textContent=scenario().topicLabel;document.getElementById('contextLabel').textContent=scenario().contextLabel;
  renderSetup();showScreen('setup');
}

function renderSetup(){
  const s=scenario();
  document.getElementById('scenarioOptions').innerHTML=SCENARIOS[state.category].map(x=>`<button type="button" class="option-card ${x.id===state.scenarioId?'selected':''}" onclick="selectScenario('${x.id}')"><strong>${escapeHtml(x.title)}</strong><span>${escapeHtml(x.description)}</span></button>`).join('');
  const ordered=[...AVATARS].sort((a,b)=>{const ai=s.recommended.indexOf(a.id),bi=s.recommended.indexOf(b.id);return (ai<0?99:ai)-(bi<0?99:bi)});
  document.getElementById('avatarOptions').innerHTML=ordered.map(a=>`<div class="avatar-card ${a.id===state.avatarId?'selected':''}" role="button" tabindex="0" onclick="selectAvatar('${a.id}')" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();selectAvatar('${a.id}')}">${s.recommended.includes(a.id)?'<span class="avatar-recommended">おすすめ</span>':''}<button class="voice-preview" type="button" aria-label="声を試す" onclick="event.stopPropagation();previewAvatarVoice('${a.id}')">🔊</button><img src="${avatarImage(a.id,'positive',true)}" alt="${escapeHtml(a.name)}"><span class="avatar-card-body"><strong>${escapeHtml(a.name)}</strong><small>${escapeHtml(a.age)}・${escapeHtml(a.role)}</small></span></div>`).join('');
  document.getElementById('personaOptions').innerHTML=PERSONAS.map(p=>`<button type="button" class="persona-btn ${p.id===state.persona?'selected':''}" title="${escapeHtml(p.description)}" onclick="selectPersona('${p.id}')"><span>${p.emoji}</span>${escapeHtml(p.label)}</button>`).join('');
  document.getElementById('difficultyOptions').innerHTML=DIFFICULTIES.map(d=>`<button type="button" class="diff-btn ${d.id===state.difficulty?'selected':''}" onclick="selectDifficulty('${d.id}')">${escapeHtml(d.label)}<small>${escapeHtml(d.description)}</small></button>`).join('');
  document.getElementById('modePractice').classList.toggle('selected',state.mode==='practice');document.getElementById('modeChallenge').classList.toggle('selected',state.mode==='challenge');
  document.getElementById('interactionVoice').classList.toggle('selected',state.interaction==='voice');document.getElementById('interactionText').classList.toggle('selected',state.interaction==='text');
  document.getElementById('setupTtsEngineSelect').value=state.ttsEngineOverride;document.getElementById('setupVoiceSelect').value=state.voiceOverride;document.getElementById('setupKokoroVoiceSelect').value=state.kokoroVoiceOverride;updateVoiceFieldVisibility();renderKokoroStatus();updateSummary();
}
function selectScenario(id){state.scenarioId=id;const s=scenario();state.avatarId=s.recommended[0];document.getElementById('topicLabel').textContent=s.topicLabel;document.getElementById('contextLabel').textContent=s.contextLabel;renderSetup()}
function selectAvatar(id){state.avatarId=id;preloadAvatar(id);renderSetup()}
function selectPersona(id){state.persona=id;renderSetup()}
function selectDifficulty(id){state.difficulty=id;renderSetup()}
function selectMode(id){state.mode=id;renderSetup()}
function selectInteraction(id){state.interaction=id;renderSetup()}
function selectTtsEngineOverride(value){state.ttsEngineOverride=value;updateVoiceFieldVisibility();updateSummary()}
function selectVoiceOverride(value){state.voiceOverride=value;updateSummary()}
function selectKokoroVoiceOverride(value){state.kokoroVoiceOverride=value;updateSummary()}
function updateSummary(){const s=scenario(),a=avatar(),p=persona(),d=difficulty();document.getElementById('summaryAvatar').src=avatarImage(a.id,'positive',true);document.getElementById('summaryName').textContent=a.name;document.getElementById('summaryRole').textContent=`${a.industry}・${a.role}`;document.getElementById('summaryCategory').textContent=CATEGORY_LABELS[state.category];document.getElementById('summaryScenario').textContent=s.title;document.getElementById('summaryPersona').textContent=p.label;document.getElementById('summaryDifficulty').textContent=d.label;document.getElementById('summaryInteraction').textContent=state.interaction==='voice'?'音声会話':'テキスト';const voiceSummary=document.getElementById('summaryVoice');if(voiceSummary)voiceSummary.textContent=voiceSummaryLabel()}

async function beginRoleplay(){
  const s=scenario(),a=avatar();
  state.topic=document.getElementById('topicInput').value.trim();state.context=document.getElementById('contextInput').value.trim();state.timeLimit=Number(document.getElementById('timeLimitSelect').value);state.timeLeft=state.timeLimit;
  state.turn=0;state.phaseIndex=0;state.conversation=[];state.events=[];state.trust={easy:58,normal:50,hard:42}[state.difficulty];state.interest={easy:52,normal:45,hard:38}[state.difficulty];state.stress={easy:14,normal:20,hard:28}[state.difficulty];state.startedAt=Date.now();state.isBusy=false;state.currentEmotion='neutral';state.audioStats={speechTurns:0,fillerCount:0,totalChars:0,totalSeconds:0};state.voiceSessionActive=false;
  document.getElementById('customerName').textContent=a.name;document.getElementById('customerRole').textContent=`${a.industry}・${a.role}｜今回の役：${s.sceneRole}`;document.getElementById('objectiveText').textContent=s.objective;document.getElementById('messageList').innerHTML='';document.getElementById('hintCard').classList.remove('visible');document.getElementById('hintButton').style.display=state.mode==='practice'?'':'none';
  preloadAvatar(a.id);setAvatarEmotion('neutral');renderPhases();updateMeters();renderTimer();showScreen('roleplay');startTimer();updateVoiceBanner();
  addMessage('ai',s.opening);state.conversation.push({role:'assistant',text:s.opening});
  if(state.interaction==='voice'&&settings.handsFree){state.voiceSessionActive=await prepareMicrophone();updateVoiceBanner()}
  if(settings.speech&&state.interaction==='voice')await speakText(s.opening,{resumeListening:state.voiceSessionActive});else if(state.voiceSessionActive)setTimeout(()=>startListening(false),300);
}
function startTimer(){clearInterval(state.timerId);if(!state.timeLimit){renderTimer();return}state.timerId=setInterval(()=>{state.timeLeft--;renderTimer();if(state.timeLeft<=0){clearInterval(state.timerId);state.timerId=null;toast('制限時間になりました');finishRoleplay()}},1000)}
function renderTimer(){const el=document.getElementById('timerDisplay');if(!state.timeLimit){el.textContent='∞';return}const sec=Math.max(0,state.timeLeft),m=Math.floor(sec/60),s=sec%60;el.textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function renderPhases(){const s=scenario();document.getElementById('phasePills').innerHTML=s.phases.map((p,i)=>`<span class="phase-pill ${i===state.phaseIndex?'active':''}">${escapeHtml(p)}</span>`).join('')}
function addMessage(role,text,meta=''){const now=new Date();const list=document.getElementById('messageList');const row=document.createElement('div');row.className=`message ${role}`;row.innerHTML=`<div><div class="bubble">${escapeHtml(text)}</div><div class="bubble-meta">${meta||now.toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})}</div></div>`;list.appendChild(row);list.scrollTop=list.scrollHeight}
function showTyping(){const list=document.getElementById('messageList');const row=document.createElement('div');row.id='typingRow';row.className='message ai';row.innerHTML='<div class="bubble"><span class="typing"><i></i><i></i><i></i></span></div>';list.appendChild(row);list.scrollTop=list.scrollHeight}
function hideTyping(){document.getElementById('typingRow')?.remove()}
function autoResize(el){el.style.height='48px';el.style.height=Math.min(el.scrollHeight,120)+'px'}
function handleInputKey(e){if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendUserMessage()}}
function insertPhrase(text){const el=document.getElementById('messageInput');el.value=text;autoResize(el);el.focus()}

async function sendUserMessage(options={}){
  const input=document.getElementById('messageInput'),text=input.value.trim();if(!text||state.isBusy)return;
  if(isListening){recognitionFinalText='';try{recognition.abort()}catch{}}
  state.isBusy=true;document.getElementById('sendButton').disabled=true;input.value='';autoResize(input);addMessage('user',text);state.conversation.push({role:'user',text});state.turn++;
  const analysis=analyzeUserMessage(text);state.events.push(analysis);if(options.source==='speech'){state.audioStats.speechTurns++;state.audioStats.totalChars+=text.length;state.audioStats.totalSeconds+=Math.max(.5,(options.durationMs||0)/1000);state.audioStats.fillerCount+=analysis.fillerCount}
  advancePhase(analysis);renderPhases();showTyping();setVoiceState('thinking','考えています');
  let response=null;
  if(settings.preferAI&&apiAvailable)response=await fetchAIReply(text);
  if(response){applyDeltas(response.deltas);setAvatarEmotion(response.emotion||deriveEmotion())}else{applyLocalDeltas(analysis);setAvatarEmotion(deriveEmotion());response={reply:localReply(text,analysis),emotion:deriveEmotion(),deltas:{}}}
  updateMeters();await wait(360);hideTyping();addMessage('ai',response.reply);state.conversation.push({role:'assistant',text:response.reply});state.isBusy=false;document.getElementById('sendButton').disabled=false;
  if(settings.speech&&state.interaction==='voice')await speakText(response.reply,{resumeListening:state.voiceSessionActive});else if(state.voiceSessionActive)setTimeout(()=>startListening(false),250);else setVoiceState('idle','待機中');
}

function analyzeUserMessage(text){const t=text.toLowerCase();const hasQuestion=/[?？]/.test(text)||/(どのよう|どんな|なぜ|どうして|いつ|誰|どこ|何が|教えて|伺|お聞き|具体的|背景|理由)/.test(t);const openQuestion=/(どのよう|どんな|なぜ|どうして|教えて|具体的|背景|理由|感じ)/.test(t);const empathy=/(ありがとうございます|おっしゃる|ご不安|ご心配|大変|お気持ち|申し訳|ご迷惑|理解|そうだった|なるほど|たしかに|確かに)/.test(t);const summary=/(つまり|ということ|整理すると|ここまで|認識|要するに|まとめると)/.test(t);const impact=/(影響|困る|問題|結果|このまま|どの程度|いつまで|誰に)/.test(t);const nextStep=/(次回|日程|いつまで|進め|検討事項|宿題|改めて|お約束|確認して連絡)/.test(t);const value=/(効果|価値|改善|メリット|成果|解決|実現|定着|支援)/.test(t);const pushy=/(今決め|絶対|必ず契約|とにかく|すぐ契約|買って|承認してください)/.test(t);const discount=/(値引き|安くします|割引|無料に)/.test(t);const tooLong=text.length>180;const apology=/(申し訳|すみません|お詫び)/.test(t);const boundary=/(できかね|対応できる範囲|責任者|引き継|安全|暴言|お話を続けることが難しい)/.test(t);const fillers=text.match(/(?:えー+|あの+|その+|まあ+|えっと+|なんというか|みたいな)/g)||[];return {hasQuestion,openQuestion,empathy,summary,impact,nextStep,value,pushy,discount,tooLong,apology,boundary,fillerCount:fillers.length,length:text.length}}
function applyDeltas(d={}){state.trust=clamp(state.trust+Number(d.trust||0));state.interest=clamp(state.interest+Number(d.interest||0));state.stress=clamp(state.stress+Number(d.stress||0))}
function applyLocalDeltas(a){let trust=0,interest=0,stress=0;if(a.openQuestion){trust+=3;interest+=3}if(a.empathy){trust+=4;stress-=3}if(a.summary){trust+=4;interest+=2}if(a.impact){interest+=4}if(a.nextStep){interest+=3}if(a.value){interest+=2}if(a.pushy){trust-=7;stress+=8}if(a.discount){interest-=1}if(a.tooLong){interest-=3;stress+=4}const factor={easy:1.25,normal:1,hard:.72}[state.difficulty];applyDeltas({trust:Math.round(trust*factor),interest:Math.round(interest*factor),stress:Math.round(stress*factor)})}
function advancePhase(a){const max=scenario().phases.length-1;const eventScore=state.events.reduce((sum,e)=>sum+(e.openQuestion?1:0)+(e.empathy?1:0)+(e.summary?1:0)+(e.impact?1:0)+(e.nextStep?1:0),0);const target=Math.min(max,Math.floor((state.turn+eventScore*.45)/2.5));if(target>state.phaseIndex)state.phaseIndex=target}
function updateMeters(){[['trust',state.trust],['interest',state.interest],['stress',state.stress]].forEach(([k,v])=>{document.getElementById(`${k}Bar`).style.width=`${v}%`;document.getElementById(`${k}Value`).textContent=Math.round(v)})}
function deriveEmotion(){if(state.stress>72)return'angry';if(state.trust>72&&state.interest>64)return'positive';if(state.interest>60)return'curious';if(state.trust<34)return'skeptical';return'neutral'}
function setAvatarEmotion(emotion){if(!EMOTIONS.includes(emotion))emotion='neutral';state.currentEmotion=emotion;const img=document.getElementById('avatarImage');if(img)img.src=avatarImage(state.avatarId,emotion);const labels={positive:'😊 前向きになっている',curious:'🤔 興味を持っている',neutral:'😐 様子を見ている',skeptical:'😒 警戒している',angry:'😠 不満を感じている'};document.getElementById('emotionLabel').textContent=labels[emotion]}
function preloadAvatar(id){EMOTIONS.forEach(e=>{const im=new Image();im.src=avatarImage(id,e)})}

function localReply(_text,a){const s=scenario(),p=persona();if(a.pushy)return'少し結論を急ぎすぎではないでしょうか。まず、こちらの状況を理解していただきたいです。';if(state.stress>76)return'すみません、今の進め方では話を続けにくいです。要点を整理していただけますか。';const pool=LOCAL_DIALOGUE[s.id]||[['もう少し具体的に教えていただけますか。']];const row=pool[Math.min(state.phaseIndex,pool.length-1)]||pool.at(-1);let reply=row[(state.turn-1)%row.length];const prefix={busy:'要点からお願いしたいのですが、',tough:'それだけでは判断できません。',logical:'根拠も確認したいのですが、',quiet:'そうですね……。',talkative:'そういえば関連して、',emotional:'正直に言うと、',gentle:'はい、',cautious:'少し慎重に考えたいのですが、'}[p.id]||'';if(a.empathy||a.openQuestion)reply=reply;else if(p.id==='quiet')reply=reply.split('。')[0]+'。';return prefix+reply}

async function fetchAIReply(userText){const payload={action:'reply',category:state.category,scenario:scenario(),avatar:avatar(),persona:persona(),difficulty:difficulty(),topic:state.topic,context:state.context,metrics:{trust:state.trust,interest:state.interest,stress:state.stress},phase:scenario().phases[state.phaseIndex],conversation:state.conversation.slice(-18),userText,audioStats:state.audioStats};const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),20000);try{const res=await fetch(getApiEndpoint(),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload),signal:controller.signal});if(!res.ok)throw new Error(`HTTP ${res.status}`);const data=await res.json();if(!data.reply)throw new Error('invalid reply');return data}catch(error){console.warn('AI reply fallback',error);apiAvailable=false;renderApiStatus();if(!apiFailureShown){toast('AIに接続できないため、ローカル会話へ切り替えました');apiFailureShown=true}return null}finally{clearTimeout(timeout)}}

function showHint(){const hints={sales:['まず相手の時間と面談目的を確認しましょう。','現状を尋ね、具体例や頻度を確認しましょう。','課題が続いた場合の影響まで聞きましょう。','相手の話を要約し、認識を合わせましょう。','次回までの行動・担当・日程を決めましょう。'],manager:['安心して話せる一言から始めましょう。','評価せずに、本人が感じていることを聞きましょう。','原因を決めつけず、背景や支援の必要性を確認しましょう。','本人が自分で選べる小さな行動を決めましょう。'],interview:['答えやすい質問で緊張を和らげましょう。','成果だけでなく、状況・本人の役割・行動を聞きましょう。','抽象的な回答には具体例を求めましょう。','候補者からの質問にも誠実に答えましょう。'],support:['まず不便や不満を受け止めてください。','事実と感情を分けて確認しましょう。','相手が何に困っているか、影響を確認しましょう。','対応できること・期限・次の連絡を明確にしましょう。','危険や暴言がある場合は境界を示し、引き継ぎましょう。']};const arr=hints[state.category];document.getElementById('hintText').textContent=arr[Math.min(state.phaseIndex,arr.length-1)];document.getElementById('hintCard').classList.add('visible')}
function requestEndRoleplay(){document.getElementById('endModal').classList.add('show')}
function closeEndModal(){document.getElementById('endModal').classList.remove('show')}
async function finishRoleplay(){if(state.isBusy)return;closeEndModal();clearInterval(state.timerId);state.timerId=null;stopVoiceRuntime(true);document.getElementById('loadingOverlay').classList.add('show');let result=null;if(settings.preferAI&&apiAvailable)result=await fetchAIEvaluation();if(!result)result=buildLocalEvaluation();state.lastResult=result;saveResult(result);renderResults(result);document.getElementById('loadingOverlay').classList.remove('show');showScreen('results')}
async function fetchAIEvaluation(){const payload={action:'evaluate',category:state.category,scenario:scenario(),avatar:avatar(),persona:persona(),difficulty:difficulty(),topic:state.topic,context:state.context,metrics:{trust:state.trust,interest:state.interest,stress:state.stress},conversation:state.conversation,audioStats:state.audioStats};const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),25000);try{const res=await fetch(getApiEndpoint(),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload),signal:controller.signal});if(!res.ok)return null;return normalizeEvaluation(await res.json())}catch{return null}finally{clearTimeout(timeout)}}
function normalizeEvaluation(data){if(!data||!Array.isArray(data.scores))return null;const expected=RUBRICS[state.category];const scores=expected.map((name,i)=>({name,score:clamp(Number(data.scores.find(s=>s.name===name)?.score??data.scores[i]?.score??60))}));const total=Math.round(scores.reduce((s,x)=>s+x.score,0)/scores.length);return {id:globalThis.crypto?.randomUUID?.()||String(Date.now()),date:new Date().toISOString(),category:state.category,scenarioId:state.scenarioId,scenarioTitle:scenario().title,avatarId:state.avatarId,avatarName:avatar().name,persona:persona().label,difficulty:difficulty().label,interaction:state.interaction,total,scores,headline:data.headline||headlineFor(total),summary:data.summary||summaryFor(total),good:data.good||'相手の発言に応じて対話を継続できました。',improve:data.improve||'相手の言葉を要約し、もう一段具体的な質問をしましょう。',nextPhrase:data.nextPhrase||defaultNextPhrase(),hiddenNeed:data.hiddenNeed||scenario().hiddenNeed,conversation:[...state.conversation],duration:Math.max(1,Math.round((Date.now()-state.startedAt)/1000)),metrics:{trust:state.trust,interest:state.interest,stress:state.stress},audioStats:{...state.audioStats}}}
function buildLocalEvaluation(){const e=state.events,cnt=k=>e.filter(x=>x[k]).length;const q=cnt('hasQuestion'),open=cnt('openQuestion'),emp=cnt('empathy'),sum=cnt('summary'),imp=cnt('impact'),next=cnt('nextStep'),val=cnt('value'),push=cnt('pushy'),long=cnt('tooLong'),boundary=cnt('boundary'),apology=cnt('apology');const base=48;let raw;if(state.category==='sales')raw=[base+emp*7+Math.min(q,3)*5-push*10,base+Math.min(q,5)*8+open*4,base+emp*9+sum*8-long*4,base+open*6+imp*10,base+val*10+sum*4,base+next*16+Math.max(0,state.interest-45)*.25];else if(state.category==='manager')raw=[base+emp*10-push*8,base+open*8+q*5,base+emp*9+sum*7,base+sum*8+q*4,base+open*6+imp*8,base+next*16];else if(state.category==='interview')raw=[base+emp*7,base+q*7+open*5,base+open*9+imp*5,base+sum*5+imp*8,base+Math.min(q,4)*5-push*8,base+next*7+emp*5];else raw=[base+emp*8+apology*7,base+q*8+sum*4,base+imp*10+open*4,base+sum*8-long*5,base+next*11+val*5,base+boundary*11+Math.max(0,50-state.stress)*.15];const diffAdj={easy:4,normal:0,hard:-3}[state.difficulty];const fillerPenalty=Math.min(6,state.audioStats.fillerCount*.8);const scores=RUBRICS[state.category].map((name,i)=>({name,score:Math.round(clamp(raw[i]+diffAdj-(i===1?fillerPenalty:0),30,96))}));let total=Math.round(scores.reduce((s,x)=>s+x.score,0)/scores.length);total=Math.round(clamp(total+(state.trust-50)*.08+(state.interest-45)*.06-(state.stress-20)*.06,25,98));const strengths=[];if(emp)strengths.push('相手の感情や発言を受け止める表現ができました');if(open)strengths.push('答えを限定しない質問で、相手に考えて話してもらえました');if(sum)strengths.push('相手の話を整理し、認識を合わせようとしました');if(next)strengths.push('次の行動を具体化しようとしました');const improves=[];if(q<2)improves.push('説明よりも質問を増やし、相手の状況を具体化しましょう');if(!emp)improves.push('相手の言葉を受け止める一言を入れてから質問しましょう');if(!sum)improves.push('途中で「つまり〜という理解で合っていますか」と要約しましょう');if(!next)improves.push('最後に次の行動・期限・担当を確認しましょう');if(long)improves.push('一度の発言を短くし、相手が話す余白をつくりましょう');if(state.audioStats.fillerCount>=4)improves.push('「えー」「あのー」を減らし、一呼吸置いてから話しましょう');return {id:globalThis.crypto?.randomUUID?.()||String(Date.now()),date:new Date().toISOString(),category:state.category,scenarioId:state.scenarioId,scenarioTitle:scenario().title,avatarId:state.avatarId,avatarName:avatar().name,persona:persona().label,difficulty:difficulty().label,interaction:state.interaction,total,scores,headline:headlineFor(total),summary:summaryFor(total),good:strengths[0]||'相手の発言に合わせて会話を進め、最後まで対話を継続できました。',improve:improves[0]||'良い流れでした。次回は相手の言葉を一度要約してから、さらに一段深い質問をしてみましょう。',nextPhrase:defaultNextPhrase(),hiddenNeed:scenario().hiddenNeed,conversation:[...state.conversation],duration:Math.max(1,Math.round((Date.now()-state.startedAt)/1000)),metrics:{trust:state.trust,interest:state.interest,stress:state.stress},audioStats:{...state.audioStats}}}
function headlineFor(score){if(score>=90)return'相手の本音と次の行動を引き出せました';if(score>=80)return'実践で通用する良い対話でした';if(score>=70)return'基本を押さえた対話でした';if(score>=60)return'改善点が明確になりました';return'まずは質問と傾聴から整えましょう'}
function summaryFor(score){if(score>=85)return'質問・傾聴・行動合意のバランスが良く、相手が話しやすい流れを作れています。';if(score>=70)return'相手の発言を受け止めながら進められました。次回は質問の深さと要約を意識しましょう。';return'説明を急がず、相手の状況や気持ちを一つずつ確認することで、信頼と情報量が高まります。'}
function defaultNextPhrase(){return {sales:'「今のお話を整理すると、最も大きい課題は〇〇という理解で合っていますか？」',manager:'「今の状況を変えるために、まず自分で試せそうなことは何ですか？」',interview:'「その成果の中で、あなた自身が判断し行動した部分を具体的に教えてください。」',support:'「ご不便をおかけして申し訳ありません。まず、いつまでに何が必要か確認させてください。」'}[state.category]}
function saveResult(result){const h=loadHistory();h.unshift(result);saveHistory(h)}
function renderResults(r){document.getElementById('scoreRing').style.setProperty('--score',r.total);document.getElementById('totalScore').textContent=r.total;const rank=r.total>=90?'S':r.total>=80?'A':r.total>=70?'B':r.total>=60?'C':'D';document.getElementById('rankBadge').textContent=`${rank}ランク`;document.getElementById('resultHeadline').textContent=r.headline;document.getElementById('resultSummary').textContent=r.summary;document.getElementById('goodFeedback').textContent=r.good;document.getElementById('improveFeedback').textContent=r.improve;document.getElementById('nextPhraseFeedback').textContent=r.nextPhrase;document.getElementById('hiddenNeedFeedback').textContent=r.hiddenNeed;document.getElementById('scoreList').innerHTML=r.scores.map(x=>`<div class="score-item"><span>${escapeHtml(x.name)}</span><div class="score-bar"><i style="width:${x.score}%"></i></div><strong>${x.score}</strong></div>`).join('');document.getElementById('transcriptList').innerHTML=r.conversation.map(m=>`<div class="transcript-line"><strong>${m.role==='user'?'あなた':escapeHtml(r.avatarName||'相手')}</strong><span>${escapeHtml(m.text)}</span></div>`).join('');const as=r.audioStats||{};document.getElementById('speechTurnMetric').textContent=as.speechTurns||0;document.getElementById('fillerMetric').textContent=as.fillerCount||0;document.getElementById('avgLengthMetric').textContent=as.speechTurns?Math.round((as.totalChars||0)/as.speechTurns):0;applyPlanPreview()}
function retryRoleplay(){showScreen('setup');renderSetup()}

function renderHome(){const h=loadHistory(),count=h.length,avg=count?Math.round(h.reduce((s,x)=>s+x.total,0)/count):null,best=count?Math.max(...h.map(x=>x.total)):null;document.getElementById('homeTotalCount').textContent=count;document.getElementById('homeAverage').textContent=avg??'--';document.getElementById('homeBest').textContent=best??'--';document.getElementById('homeStreak').textContent=calculateStreak(h);document.getElementById('homeAvatarStrip').innerHTML=AVATARS.map(a=>`<button class="avatar-chip" type="button" onclick="startSetupForAvatar('${a.id}')"><img src="${avatarImage(a.id,'positive',true)}" alt="${escapeHtml(a.name)}"><strong>${escapeHtml(a.name)}</strong></button>`).join('');const recent=document.getElementById('recentResult');if(!h.length)recent.innerHTML='<div class="empty-state" style="width:100%">まだ結果がありません。最初のロープレに挑戦しましょう。</div>';else{const r=h[0];recent.innerHTML=`<div><div class="eyebrow" style="margin-bottom:5px">${escapeHtml(CATEGORY_LABELS[r.category])}</div><h3>${escapeHtml(r.scenarioTitle)}</h3><p style="font-size:12px;color:var(--muted);margin:0">${new Date(r.date).toLocaleString('ja-JP')}・${escapeHtml(r.avatarName||'相手')}・${escapeHtml(r.difficulty)}</p></div><div class="score-pill"><strong>${r.total}</strong><span>score</span></div>`}}
function startSetupForAvatar(id){const a=avatar(id);startSetup(a.categories[0]||'sales');state.avatarId=id;renderSetup()}
function calculateStreak(history){if(!history.length)return 0;const days=[...new Set(history.map(x=>new Date(x.date).toLocaleDateString('sv-SE')))].sort().reverse();let streak=0,cursor=new Date();cursor.setHours(0,0,0,0);const first=new Date(days[0]+'T00:00:00');if((cursor-first)/86400000>1)return 0;if((cursor-first)/86400000>=1)cursor=first;for(const d of days){const date=new Date(d+'T00:00:00');if(Math.round((cursor-date)/86400000)===0){streak++;cursor.setDate(cursor.getDate()-1)}else if(date<cursor)break}return streak}
function renderHistory(){const h=loadHistory(),count=h.length,avg=count?Math.round(h.reduce((s,x)=>s+x.total,0)/count):null,best=count?Math.max(...h.map(x=>x.total)):null;document.getElementById('historyCount').textContent=count+'回';document.getElementById('historyAverage').textContent=avg??'--';document.getElementById('historyBest').textContent=best??'--';document.getElementById('historyList').innerHTML=count?h.map(r=>`<div class="history-item"><img src="${avatarImage(avatar(r.avatarId).id,'positive',true)}" alt=""><div><h3>${escapeHtml(r.scenarioTitle)} <span style="font-weight:600;color:var(--muted)">／ ${escapeHtml(CATEGORY_LABELS[r.category])}</span></h3><p>${new Date(r.date).toLocaleString('ja-JP')}・${escapeHtml(r.avatarName||'相手')}・${escapeHtml(r.persona)}・${escapeHtml(r.difficulty)}</p></div><div class="history-score">${r.total}</div></div>`).join(''):'<div class="empty-state">成績はまだありません。</div>'}

function loadVoices(){if(!('speechSynthesis'in window))return;availableVoices=window.speechSynthesis.getVoices()||[];refreshVoiceSelects()}
function refreshVoiceSelects(){const japanese=availableVoices.filter(v=>/^ja/i.test(v.lang));const voices=japanese.length?japanese:availableVoices;['setupVoiceSelect','settingsVoiceSelect'].forEach(id=>{const select=document.getElementById(id);if(!select)return;const current=id==='setupVoiceSelect'?state.voiceOverride:settings.voiceURI;select.innerHTML='<option value="auto">アバターに合わせて自動選択</option>'+voices.map(v=>`<option value="${escapeHtml(v.voiceURI)}">${escapeHtml(v.name)}（${escapeHtml(v.lang)}）</option>`).join('');select.value=[...select.options].some(o=>o.value===current)?current:'auto'})}
function refreshKokoroVoiceSelects(){['setupKokoroVoiceSelect','settingsKokoroVoiceSelect'].forEach(id=>{const select=document.getElementById(id);if(!select)return;const current=id==='setupKokoroVoiceSelect'?state.kokoroVoiceOverride:settings.kokoroVoice;select.innerHTML=KOKORO_VOICES.map(v=>`<option value="${v.id}">${escapeHtml(v.label)}</option>`).join('');select.value=KOKORO_VOICES.some(v=>v.id===current)?current:'auto'})}
function chooseVoice(a=avatar()){const requested=state.voiceOverride!=='auto'?state.voiceOverride:settings.voiceURI;if(requested&&requested!=='auto'){const exact=availableVoices.find(v=>v.voiceURI===requested);if(exact)return exact}const ja=availableVoices.filter(v=>/^ja/i.test(v.lang));const pool=ja.length?ja:availableVoices;for(const keyword of a.voice.keywords||[]){const found=pool.find(v=>v.name.toLowerCase().includes(keyword.toLowerCase()));if(found)return found}return pool[AVATARS.indexOf(a)%Math.max(1,pool.length)]||availableVoices[0]||null}
function chosenKokoroVoice(a=avatar()){const requested=state.kokoroVoiceOverride!=='auto'?state.kokoroVoiceOverride:settings.kokoroVoice;return requested&&requested!=='auto'?requested:(a.voice.kokoro||'jm_kumo')}
function selectedTtsEngine(){return state.ttsEngineOverride!=='auto'?state.ttsEngineOverride:settings.ttsEngine}
function isIOSLike(){return /iPad|iPhone|iPod/.test(navigator.userAgent)||(/Macintosh/.test(navigator.userAgent)&&navigator.maxTouchPoints>1)}
function canUseKokoro(){return location.protocol!=='file:'&&typeof Worker!=='undefined'&&typeof Audio!=='undefined'&&!isIOSLike()}
function resolvedTtsEngine(){const selected=selectedTtsEngine();if(selected==='browser')return'browser';if(selected==='kokoro')return kokoroStatus==='error'?'browser':'kokoro';if(kokoroStatus==='error')return'browser';if(kokoroStatus==='ready')return'kokoro';const lowMemory=Number(navigator.deviceMemory||8)<4;return canUseKokoro()&&!lowMemory?'kokoro':'browser'}
function voiceSummaryLabel(){const engine=resolvedTtsEngine();if(engine==='kokoro'){const id=chosenKokoroVoice();return`Kokoro・${KOKORO_VOICES.find(v=>v.id===id)?.label||id}`}const v=chooseVoice();return v?`端末音声・${v.name}`:'端末の日本語音声'}
function updateVoiceFieldVisibility(){const setupEngine=state.ttsEngineOverride==='auto'?settings.ttsEngine:state.ttsEngineOverride;const settingsEngine=settings.ttsEngine;document.getElementById('setupKokoroVoiceField')?.classList.toggle('hidden',setupEngine==='browser');document.getElementById('setupBrowserVoiceField')?.classList.toggle('hidden',setupEngine==='kokoro');document.getElementById('settingsKokoroVoiceRow')?.classList.toggle('hidden',settingsEngine==='browser');document.getElementById('settingsBrowserVoiceRow')?.classList.toggle('hidden',settingsEngine==='kokoro')}
async function previewAvatarVoice(id){await speakText(avatar(id).sample,{avatarId:id,resumeListening:false,preview:true})}
async function previewCurrentVoice(){const onSettings=document.getElementById('screen-settings')?.classList.contains('active');if(!onSettings){await speakText(avatar().sample,{resumeListening:false,preview:true});return}const previous={engine:state.ttsEngineOverride,browser:state.voiceOverride,kokoro:state.kokoroVoiceOverride};state.ttsEngineOverride='auto';state.voiceOverride='auto';state.kokoroVoiceOverride='auto';try{await speakText(avatar().sample,{resumeListening:false,preview:true})}finally{state.ttsEngineOverride=previous.engine;state.voiceOverride=previous.browser;state.kokoroVoiceOverride=previous.kokoro}}
function changeTtsEngine(value){settings.ttsEngine=value;saveSettings();updateVoiceFieldVisibility();renderKokoroStatus()}
function changeSettingsVoice(value){settings.voiceURI=value;saveSettings()}
function changeKokoroVoice(value){settings.kokoroVoice=value;saveSettings()}
function changeSpeechRate(value){settings.speechRate=Number(value);saveSettings();document.getElementById('speechRateValue').textContent=Number(value).toFixed(2)}
function renderSettings(){document.getElementById('aiSwitch').classList.toggle('on',settings.preferAI);document.getElementById('speechSwitch').classList.toggle('on',settings.speech);document.getElementById('handsFreeSwitch').classList.toggle('on',settings.handsFree);document.getElementById('autoSendSwitch').classList.toggle('on',settings.autoSend);document.getElementById('premiumSwitch')?.classList.toggle('on',settings.premiumPreview);const endpointInput=document.getElementById('apiEndpointInput');if(endpointInput)endpointInput.value=settings.apiEndpoint||'';document.getElementById('settingsTtsEngineSelect').value=settings.ttsEngine;document.getElementById('speechRateRange').value=settings.speechRate;document.getElementById('speechRateValue').textContent=Number(settings.speechRate).toFixed(2);refreshVoiceSelects();refreshKokoroVoiceSelects();document.getElementById('settingsVoiceSelect').value=settings.voiceURI;document.getElementById('settingsKokoroVoiceSelect').value=settings.kokoroVoice;updateVoiceFieldVisibility();renderKokoroStatus();renderApiStatus();applyPlanPreview()}
function toggleSetting(key){settings[key]=!settings[key];saveSettings();toast(settings[key]?'オンにしました':'オフにしました');if(key==='preferAI')probeAPI()}
function changeApiEndpoint(value){settings.apiEndpoint=String(value||'').trim();try{localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings))}catch{}apiAvailable=false;renderApiStatus()}
async function testApiEndpoint(){changeApiEndpoint(document.getElementById('apiEndpointInput')?.value||'');toast('AI接続を確認しています');await probeAPI();toast(apiAvailable?'AIエンドポイントへ接続できました':'接続できません。URLとCORS設定を確認してください')}
function togglePremiumPreview(){settings.premiumPreview=!settings.premiumPreview;saveSettings();toast(settings.premiumPreview?'プレミアム表示に切り替えました':'無料プラン表示に切り替えました')}
function applyPlanPreview(){document.body.classList.toggle('free-plan-preview',!settings.premiumPreview);const banner=document.getElementById('planPreviewBanner');if(banner)banner.hidden=settings.premiumPreview}
function downloadLatestReport(){const r=state.lastResult||loadHistory()[0];if(!r){toast('出力できる結果がありません');return}const lines=[`AI ROLEPLAY STUDIO トレーニング結果`,`日時: ${new Date(r.date).toLocaleString('ja-JP')}`,`カテゴリー: ${CATEGORY_LABELS[r.category]||r.category}`,`シナリオ: ${r.scenarioTitle}`,`相手: ${r.avatarName||''}`,`総合スコア: ${r.total}/100`,``,`項目別スコア`,...(r.scores||[]).map(x=>`${x.name}: ${x.score}`),``,`良かった点`,r.good||'',``,`改善ポイント`,r.improve||'',``,`次に使う一言`,r.nextPhrase||'',``,`相手の本音`,r.hiddenNeed||'',``,`会話記録`,...(r.conversation||[]).map(m=>`${m.role==='user'?'あなた':r.avatarName||'相手'}: ${m.text}`)];downloadText(`roleplay-report-${new Date(r.date).toISOString().slice(0,10)}.txt`,lines.join('\n'))}
function exportAllHistory(){const h=loadHistory();if(!h.length){toast('出力できる履歴がありません');return}downloadText(`roleplay-history-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(h,null,2),'application/json')}
function downloadText(name,text,type='text/plain'){const blob=new Blob([text],{type:`${type};charset=utf-8`});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function confirmResetData(){if(confirm('成績・設定・履歴をすべて削除します。よろしいですか？')){try{localStorage.removeItem(APP_KEY);localStorage.removeItem(SETTINGS_KEY)}catch{}settings={...DEFAULT_SETTINGS};renderHome();renderSettings();toast('データを削除しました')}}

function setupKokoroWorker(){if(kokoroWorker)return kokoroWorker;if(!canUseKokoro())throw new Error(location.protocol==='file:'?'KokoroはHTTPSまたはlocalhostで利用してください':'この端末ではKokoroを利用できません');kokoroWorker=new Worker(new URL('kokoro-worker.js',document.baseURI),{type:'module'});kokoroWorker.onmessage=event=>{const msg=event.data||{};if(msg.type==='progress'){kokoroStatus='loading';kokoroProgress=clamp(Number(msg.progress||0),0,100);kokoroStatusDetail=msg.detail||'モデルを読み込み中';renderKokoroStatus();return}if(msg.type==='ready'){kokoroStatus='ready';kokoroProgress=100;kokoroStatusDetail='準備完了';kokoroLoadResolve?.(true);kokoroLoadPromise=null;kokoroLoadResolve=null;kokoroLoadReject=null;renderKokoroStatus();return}if(msg.type==='audio'){const pending=kokoroPending.get(msg.id);if(pending){clearTimeout(pending.timer);kokoroPending.delete(msg.id);pending.resolve(msg)}return}if(msg.type==='error'){const error=new Error(msg.message||'Kokoro音声の処理に失敗しました');if(msg.id&&kokoroPending.has(msg.id)){const pending=kokoroPending.get(msg.id);clearTimeout(pending.timer);pending.reject(error);kokoroPending.delete(msg.id)}else{kokoroStatus='error';kokoroStatusDetail=error.message;kokoroLoadReject?.(error);kokoroLoadPromise=null;kokoroLoadResolve=null;kokoroLoadReject=null;renderKokoroStatus()}return}};kokoroWorker.onerror=event=>{const error=new Error(event.message||'Kokoro音声ワーカーを開始できませんでした');kokoroStatus='error';kokoroStatusDetail=error.message;kokoroLoadReject?.(error);kokoroLoadPromise=null;kokoroLoadResolve=null;kokoroLoadReject=null;for(const pending of kokoroPending.values()){clearTimeout(pending.timer);pending.reject(error)}kokoroPending.clear();renderKokoroStatus()};return kokoroWorker}
function ensureKokoroReady(){if(kokoroStatus==='ready')return Promise.resolve(true);if(kokoroLoadPromise)return kokoroLoadPromise;kokoroStatus='loading';kokoroProgress=1;kokoroStatusDetail='Kokoroライブラリを読み込み中';renderKokoroStatus();kokoroLoadPromise=new Promise((resolve,reject)=>{kokoroLoadResolve=resolve;kokoroLoadReject=reject;try{setupKokoroWorker().postMessage({type:'load',model:KOKORO_MODEL,dtype:KOKORO_DTYPE})}catch(error){kokoroStatus='error';kokoroStatusDetail=error.message;kokoroLoadPromise=null;kokoroLoadResolve=null;kokoroLoadReject=null;reject(error);renderKokoroStatus()}});return kokoroLoadPromise}
async function prepareKokoroModel(){try{toast('Kokoroモデルを準備します。初回は約90MBを取得します');await ensureKokoroReady();toast('Kokoro音声の準備が完了しました')}catch(error){toast(error.message||'Kokoro音声を準備できませんでした')}}
function renderKokoroStatus(){const status=document.getElementById('kokoroStatusText'),detail=document.getElementById('kokoroStatusDetail'),bar=document.getElementById('kokoroProgressFill'),button=document.getElementById('kokoroLoadButton'),notice=document.getElementById('setupKokoroNotice');const labels={idle:'未準備',loading:`準備中 ${Math.round(kokoroProgress)}%`,ready:'準備完了',error:'利用できません'};if(status)status.textContent=labels[kokoroStatus]||labels.idle;if(detail)detail.textContent=kokoroStatus==='idle'?'初回利用時に約90MBのモデルを取得し、ブラウザへキャッシュします。':kokoroStatusDetail;if(bar){bar.style.width=`${kokoroStatus==='idle'?0:kokoroProgress}%`;bar.parentElement?.classList.toggle('error',kokoroStatus==='error')}if(button){button.disabled=kokoroStatus==='loading'||kokoroStatus==='ready';button.textContent=kokoroStatus==='ready'?'準備済み':kokoroStatus==='loading'?'準備中…':'モデルを準備'}if(notice){const engine=resolvedTtsEngine();notice.className=`kokoro-notice ${engine==='kokoro'?'active':''}`;notice.innerHTML=engine==='kokoro'?`<strong>Kokoro音声を使用</strong><span>${kokoroStatus==='ready'?'端末内で音声を生成します。':location.protocol==='file:'?'Kokoroは公開URLまたはlocalhostで動作します。':'初回のみ約90MBを取得します。生成後の文章は外部の音声APIへ送られません。'}</span>`:'<strong>端末標準音声を使用</strong><span>Kokoroが利用できない端末では自動的にこちらへ切り替わります。</span>'}}
function requestKokoroAudio(text,voice,speed){return new Promise((resolve,reject)=>{const id=`tts-${Date.now()}-${++kokoroRequestId}`;const timer=setTimeout(()=>{if(kokoroPending.has(id)){kokoroPending.delete(id);reject(new Error('Kokoro音声の生成がタイムアウトしました'))}},60000);kokoroPending.set(id,{resolve,reject,timer});kokoroGenerating=true;setupKokoroWorker().postMessage({type:'generate',id,text,voice,speed})})}
function stopCurrentSpeech(invalidate=true){if(invalidate)speechToken++;if('speechSynthesis'in window)window.speechSynthesis.cancel();if(currentAudio){try{currentAudio.pause();currentAudio.currentTime=0}catch{}currentAudio=null}if(currentAudioUrl){URL.revokeObjectURL(currentAudioUrl);currentAudioUrl=''}kokoroGenerating=false;document.getElementById('avatarStage')?.classList.remove('speaking')}
function isSpeechOutputActive(){return Boolean(window.speechSynthesis?.speaking||kokoroGenerating||(currentAudio&&!currentAudio.paused&&!currentAudio.ended))}
function afterSpeech(token,{resumeListening,preview},resolve){if(token!==speechToken){resolve();return}document.getElementById('avatarStage')?.classList.remove('speaking');kokoroGenerating=false;if(!preview&&resumeListening&&state.voiceSessionActive&&isRoleplayActive()){setVoiceState('idle','次に話してください');setTimeout(()=>startListening(false),300)}else if(!preview)setVoiceState('idle','待機中');resolve()}
function speakWithBrowser(text,options,token){return new Promise(resolve=>{if(!('speechSynthesis'in window)){resolve();return}const a=avatar(options.avatarId);const utter=new SpeechSynthesisUtterance(text);utter.lang='ja-JP';utter.rate=clamp(a.voice.rate*Number(settings.speechRate||1),.7,1.35);utter.pitch=clamp(a.voice.pitch,.65,1.35);const selected=chooseVoice(a);if(selected)utter.voice=selected;let done=false;const finish=()=>{if(done)return;done=true;clearTimeout(fallback);afterSpeech(token,options,resolve)};utter.onstart=()=>{if(isListening){try{recognition.abort()}catch{}}document.getElementById('avatarStage')?.classList.add('speaking');if(!options.preview)setVoiceState('speaking','AIが話しています')};utter.onend=finish;utter.onerror=finish;const fallback=setTimeout(finish,Math.max(5000,text.length*180));window.speechSynthesis.speak(utter)})}
async function speakWithKokoro(text,options,token){const a=avatar(options.avatarId);if(isListening){try{recognition.abort()}catch{}}document.getElementById('avatarStage')?.classList.add('speaking');if(!options.preview)setVoiceState('speaking',kokoroStatus==='ready'?'Kokoro音声を生成中':'Kokoroモデルを準備中');await ensureKokoroReady();if(token!==speechToken)return;const speed=clamp(a.voice.rate*Number(settings.speechRate||1),.72,1.28);const result=await requestKokoroAudio(text,chosenKokoroVoice(a),speed);if(token!==speechToken)return;kokoroGenerating=false;const blob=new Blob([result.buffer],{type:result.mime||'audio/wav'});currentAudioUrl=URL.createObjectURL(blob);currentAudio=new Audio(currentAudioUrl);currentAudio.preload='auto';currentAudio.playsInline=true;return new Promise((resolve,reject)=>{let done=false;const finish=()=>{if(done)return;done=true;const url=currentAudioUrl;currentAudio=null;currentAudioUrl='';if(url)URL.revokeObjectURL(url);afterSpeech(token,options,resolve)};currentAudio.onplay=()=>{if(!options.preview)setVoiceState('speaking','AIが話しています')};currentAudio.onended=finish;currentAudio.onerror=()=>{finish();reject(new Error('生成した音声を再生できませんでした'))};currentAudio.play().catch(error=>{finish();reject(error)})})}
async function speakText(text,{resumeListening=true,avatarId=state.avatarId,preview=false}={}){if(!settings.speech||!text)return;const options={resumeListening,avatarId,preview};const token=++speechToken;stopCurrentSpeech(false);const engine=resolvedTtsEngine();if(engine==='kokoro'){try{await speakWithKokoro(text,options,token);return}catch(error){console.warn('Kokoro TTS fallback',error);kokoroStatus='error';kokoroStatusDetail=error.message||'Kokoro音声を利用できません';renderKokoroStatus();if(!kokoroFallbackShown){toast('Kokoro音声を利用できないため、端末音声へ切り替えました');kokoroFallbackShown=true}if(token!==speechToken)return;kokoroGenerating=false}}await speakWithBrowser(text,options,token)}
function repeatLastAIMessage(){const last=[...state.conversation].reverse().find(m=>m.role==='assistant');if(last)speakText(last.text,{resumeListening:state.voiceSessionActive});else toast('読み上げる発言がありません')}

function setupSpeechRecognition(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return;recognition=new SR();recognition.lang='ja-JP';recognition.interimResults=true;recognition.continuous=false;recognition.maxAlternatives=1;recognition.onstart=()=>{isListening=true;recognitionFinalText='';recognitionStartedAt=Date.now();document.getElementById('micButton')?.classList.add('listening');setVoiceState('listening','聞き取り中')};recognition.onresult=e=>{let interim='',final='';for(let i=e.resultIndex;i<e.results.length;i++){const part=e.results[i][0].transcript;if(e.results[i].isFinal)final+=part;else interim+=part}if(final)recognitionFinalText+=final;const input=document.getElementById('messageInput');input.value=(recognitionFinalText+interim).trim();autoResize(input)};recognition.onend=()=>{isListening=false;recognitionDuration=Math.max(0,Date.now()-recognitionStartedAt);document.getElementById('micButton')?.classList.remove('listening');const text=(recognitionFinalText||document.getElementById('messageInput')?.value||'').trim();recognitionFinalText='';if(text&&(settings.autoSend||state.voiceSessionActive)&&isRoleplayActive()&&!state.isBusy){setTimeout(()=>sendUserMessage({source:'speech',durationMs:recognitionDuration}),260)}else if(state.voiceSessionActive&&isRoleplayActive()&&!state.isBusy){setVoiceState('idle','声を待っています');setTimeout(()=>startListening(false),650)}else setVoiceState('idle','待機中')};recognition.onerror=e=>{isListening=false;document.getElementById('micButton')?.classList.remove('listening');if(e.error!=='aborted'&&e.error!=='no-speech')toast(e.error==='not-allowed'?'マイクの利用を許可してください':'音声を認識できませんでした');if(e.error==='not-allowed')state.voiceSessionActive=false;updateVoiceBanner()}}
async function prepareMicrophone(){if(!recognition){toast('このブラウザは音声認識に対応していません。ChromeまたはEdgeでお試しください。');return false}try{if(navigator.mediaDevices?.getUserMedia){const stream=await navigator.mediaDevices.getUserMedia({audio:true});stream.getTracks().forEach(t=>t.stop())}return true}catch{toast('マイクの利用を許可すると、音声会話を開始できます');return false}}
async function startListening(manual=true){if(!recognition||isListening||state.isBusy||!isRoleplayActive()||isSpeechOutputActive())return false;if(manual&&!await prepareMicrophone())return false;try{recognition.start();return true}catch{return false}}
async function toggleSpeechRecognition(){if(!recognition){toast('このブラウザは音声認識に対応していません');return}if(isListening){try{recognition.stop()}catch{};return}await startListening(true)}
async function toggleVoiceSession(){if(state.voiceSessionActive){state.voiceSessionActive=false;stopVoiceRuntime(false);updateVoiceBanner();toast('ハンズフリー音声会話を停止しました');return}if(state.interaction!=='voice')state.interaction='voice';const ok=await prepareMicrophone();if(!ok)return;state.voiceSessionActive=true;updateVoiceBanner();if(!isSpeechOutputActive()&&!state.isBusy)startListening(false)}
function updateVoiceBanner(){const active=state.voiceSessionActive;document.getElementById('voiceBanner').style.display=state.interaction==='voice'?'':'none';document.getElementById('voiceBannerTitle').textContent=active?'ハンズフリー音声会話中':'音声会話は停止中です';const engine=resolvedTtsEngine()==='kokoro'?'Kokoro音声':'端末音声';document.getElementById('voiceBannerText').textContent=active?`${engine}が話し終わると、自動でマイクが開きます。`:'開始すると、AI発話後に自動でマイクが開きます。';const btn=document.getElementById('voiceSessionButton');btn.textContent=active?'音声会話を停止':'音声会話を開始';btn.classList.toggle('active',active)}
function stopVoiceRuntime(cancelSpeech=true){state.voiceSessionActive=false;if(isListening){try{recognition.abort()}catch{}}if(cancelSpeech)stopCurrentSpeech(true);document.getElementById('avatarStage')?.classList.remove('speaking');setVoiceState('idle','待機中');if(document.getElementById('voiceBanner'))updateVoiceBanner()}
function setVoiceState(type,text){const el=document.getElementById('voiceState');if(!el)return;el.className=`voice-state ${type==='listening'?'listening':type==='speaking'?'speaking':''}`;document.getElementById('voiceStateText').textContent=text}

function renderApiStatus(){const el=document.getElementById('apiStatus'),text=document.getElementById('apiStatusText');el.classList.toggle('online',apiAvailable);text.textContent=apiAvailable?'AI接続中':'ローカルモード'}
async function probeAPI(){const endpoint=getApiEndpoint();if(!settings.preferAI||(!settings.apiEndpoint&&location.protocol==='file:')){apiAvailable=false;renderApiStatus();return}try{const res=await fetch(endpoint,{method:'GET',cache:'no-store'});const data=await res.json();apiAvailable=res.ok&&data.aiConfigured!==false;renderApiStatus()}catch{apiAvailable=false;renderApiStatus()}}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');clearTimeout(el._timer);el._timer=setTimeout(()=>el.classList.remove('show'),2500)}
function wait(ms){return new Promise(r=>setTimeout(r,ms))}

function init(){setupSpeechRecognition();loadVoices();refreshKokoroVoiceSelects();if('speechSynthesis'in window)window.speechSynthesis.onvoiceschanged=loadVoices;renderHome();renderSettings();renderKokoroStatus();probeAPI();AVATARS.slice(0,3).forEach(a=>preloadAvatar(a.id));if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('service-worker.js').catch(()=>{})}
init();

