import {cp,mkdir,rm,stat} from 'node:fs/promises';
import {build} from 'esbuild';
const files=['index.html','styles.css','app.js','service-worker.js','manifest.webmanifest','THIRD_PARTY_NOTICES.md'];
await rm('dist',{recursive:true,force:true});await mkdir('dist',{recursive:true});
await build({entryPoints:['src/local-ai.js'],bundle:true,format:'iife',target:'es2022',outfile:'dist/local-ai.js',minify:true});
await build({entryPoints:['src/local-ai-worker.js'],bundle:true,format:'esm',target:'es2022',outfile:'dist/local-ai-worker.js',minify:true});
for(const file of files)await cp(file,`dist/${file}`);
await cp('assets','dist/assets',{recursive:true});
for(const file of ['dist/index.html','dist/app.js','dist/local-ai.js','dist/local-ai-worker.js','dist/assets/icon.svg','dist/assets/avatars/suzuki/neutral.webp'])await stat(file);
console.log(`Built ${files.length+103} static assets into dist/`);
